export const GET_ERRORS = 'GET_ERRORS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ADD_FAV = 'ADD_FAV';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_FRESH_UPDATE = 'GET_FRESH_UPDATE';

export const GET_NEW_UPLOADS = 'GET_NEW_UPLOADS';

export const GET_POPULAR = 'GET_POPULAR';

export const GET_SEARCHED_COMICS = 'GET_SEARCHED_COMICS';

export const GET_DASHBOARD_RECOMMENDED_COMIC = 'GET_DASHBOARD_RECOMMENDED_COMIC';

export const GET_FAV_COMIC = 'GET_FAV_COMIC';

export const GET_FEATURED = 'GET_FEATURED';

export const GET_STUDIO = 'GET_STUDIO';

export const GET_STUDIOS = 'GET_STUDIOS';

export const GET_A_COMIC = 'GET_A_COMIC';

export const GET_A_COMIC_CHAPTER = 'GET_A_COMIC_CHAPTER';

export const GET_RECOMMENDED = 'GET_RECOMMENDED';

export const GET_COMIC_WITH_SUB_COMIC = 'GET_COMIC_WITH_SUB_COMIC';

export const GET_COMIC_WITH_SUB_COMIC_CHAPTERS = 'GET_COMIC_WITH_SUB_COMIC_CHAPTERS';

export const READER_LOADED = 'READER_LOADED';

export const READER_LOADING = 'READER_LOADING';

export const SET_CURRENT = 'SET_CURRENT';

export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_SUBSCRIPTION_DASH = 'GET_SUBSCRIPTION_DASH';

export const LOADING = 'LOADING';
